// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.24;

import "../core/EnterpriseRegistry.sol";

/// @title ZKVerifier
/// @notice Verifies Groth16 zero-knowledge proofs on-chain for enterprise batch validation.
/// @dev This contract demonstrates the ZK validium architecture where enterprises submit
///      proofs of valid transaction batches without revealing transaction data.
///      The Groth16 verifier logic is generated by SnarkJS and integrated here.
contract ZKVerifier {
    struct BatchVerification {
        address enterprise;
        bytes32 stateRoot;
        uint256 batchSize;
        bool verified;
        uint256 timestamp;
    }

    struct VerifyingKey {
        uint256[2] alfa1;
        uint256[2][2] beta2;
        uint256[2][2] gamma2;
        uint256[2][2] delta2;
        uint256[2][] IC;
    }

    EnterpriseRegistry public immutable enterpriseRegistry;

    mapping(bytes32 => BatchVerification) private batches;
    bytes32[] private batchIds;
    uint256 public totalBatches;
    uint256 public totalVerified;
    uint256 public totalTransactionsVerified;

    VerifyingKey private vk;
    bool public verifyingKeySet;

    event BatchSubmitted(
        bytes32 indexed batchId,
        address indexed enterprise,
        bytes32 stateRoot,
        uint256 batchSize,
        uint256 timestamp
    );
    event BatchVerified(
        bytes32 indexed batchId,
        address indexed enterprise,
        bool verified,
        uint256 timestamp
    );
    event VerifyingKeyUpdated(uint256 timestamp);

    error NotAuthorized();
    error VerifyingKeyNotSet();
    error BatchAlreadyExists();
    error BatchNotFound();
    error InvalidProof();
    error OnlyAdmin();

    address public admin;

    modifier onlyAdmin() {
        if (msg.sender != admin) revert OnlyAdmin();
        _;
    }

    modifier onlyAuthorizedEnterprise() {
        if (!enterpriseRegistry.isAuthorized(msg.sender)) revert NotAuthorized();
        _;
    }

    constructor(address _enterpriseRegistry) {
        enterpriseRegistry = EnterpriseRegistry(_enterpriseRegistry);
        admin = msg.sender;
    }

    /// @notice Sets the Groth16 verifying key generated by SnarkJS trusted setup.
    /// @dev Only callable by admin. The verifying key must match the circuit used for proving.
    /// @param _alfa1 The alfa1 point of the verifying key.
    /// @param _beta2 The beta2 point of the verifying key.
    /// @param _gamma2 The gamma2 point of the verifying key.
    /// @param _delta2 The delta2 point of the verifying key.
    /// @param _IC The IC points of the verifying key.
    function setVerifyingKey(
        uint256[2] calldata _alfa1,
        uint256[2][2] calldata _beta2,
        uint256[2][2] calldata _gamma2,
        uint256[2][2] calldata _delta2,
        uint256[2][] calldata _IC
    ) external onlyAdmin {
        vk.alfa1 = _alfa1;
        vk.beta2 = _beta2;
        vk.gamma2 = _gamma2;
        vk.delta2 = _delta2;
        delete vk.IC;
        for (uint256 i = 0; i < _IC.length; i++) {
            vk.IC.push(_IC[i]);
        }
        verifyingKeySet = true;
        emit VerifyingKeyUpdated(block.timestamp);
    }

    /// @notice Submits and verifies a batch proof from an enterprise.
    /// @dev The proof attests that a batch of off-chain transactions is valid
    ///      without revealing transaction data (ZK validium model).
    /// @param stateRoot The new state root after the batch.
    /// @param batchSize The number of transactions in the batch.
    /// @param a The proof point A (Groth16).
    /// @param b The proof point B (Groth16).
    /// @param c The proof point C (Groth16).
    /// @param publicSignals The public inputs to the circuit.
    /// @return batchId The unique identifier for this batch.
    function verifyBatchProof(
        bytes32 stateRoot,
        uint256 batchSize,
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata publicSignals
    ) external onlyAuthorizedEnterprise returns (bytes32 batchId) {
        if (!verifyingKeySet) revert VerifyingKeyNotSet();

        batchId = keccak256(
            abi.encodePacked(msg.sender, stateRoot, batchSize, block.timestamp)
        );
        if (batches[batchId].timestamp != 0) revert BatchAlreadyExists();

        bool proofValid = _verifyProof(a, b, c, publicSignals);

        batches[batchId] = BatchVerification({
            enterprise: msg.sender,
            stateRoot: stateRoot,
            batchSize: batchSize,
            verified: proofValid,
            timestamp: block.timestamp
        });

        batchIds.push(batchId);
        totalBatches++;

        if (proofValid) {
            totalVerified++;
            totalTransactionsVerified += batchSize;
        }

        emit BatchSubmitted(batchId, msg.sender, stateRoot, batchSize, block.timestamp);
        emit BatchVerified(batchId, msg.sender, proofValid, block.timestamp);
    }

    /// @notice Returns the details of a batch verification.
    /// @param batchId The batch to query.
    function getBatch(bytes32 batchId)
        external
        view
        returns (
            address enterprise,
            bytes32 stateRoot,
            uint256 batchSize,
            bool verified,
            uint256 timestamp
        )
    {
        BatchVerification storage b = batches[batchId];
        if (b.timestamp == 0) revert BatchNotFound();
        return (b.enterprise, b.stateRoot, b.batchSize, b.verified, b.timestamp);
    }

    /// @notice Returns all batch IDs.
    function getAllBatches() external view returns (bytes32[] memory) {
        return batchIds;
    }

    /// @notice Groth16 proof verification using precompiled contracts for elliptic curve operations.
    /// @dev Uses EIP-196 (ecAdd, ecMul) and EIP-197 (ecPairing) precompiles.
    function _verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata input
    ) internal view returns (bool) {
        require(input.length + 1 == vk.IC.length, "Invalid input length");

        uint256[2] memory vk_x = [vk.IC[0][0], vk.IC[0][1]];

        for (uint256 i = 0; i < input.length; i++) {
            uint256[2] memory mul_result = _ecMul(vk.IC[i + 1], input[i]);
            vk_x = _ecAdd(vk_x, mul_result);
        }

        return _ecPairing(
            _negate(a),
            b,
            vk.alfa1,
            vk.beta2,
            vk_x,
            vk.gamma2,
            c,
            vk.delta2
        );
    }

    /// @dev Negates a point on the BN254 curve.
    function _negate(uint256[2] calldata p) internal pure returns (uint256[2] memory) {
        uint256 q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
        if (p[0] == 0 && p[1] == 0) return [uint256(0), uint256(0)];
        return [p[0], q - (p[1] % q)];
    }

    /// @dev Elliptic curve addition using the precompile at address 0x06.
    function _ecAdd(uint256[2] memory p1, uint256[2] memory p2) internal view returns (uint256[2] memory r) {
        uint256[4] memory input_data;
        input_data[0] = p1[0];
        input_data[1] = p1[1];
        input_data[2] = p2[0];
        input_data[3] = p2[1];
        assembly {
            if iszero(staticcall(gas(), 0x06, input_data, 0x80, r, 0x40)) {
                revert(0, 0)
            }
        }
    }

    /// @dev Elliptic curve scalar multiplication using the precompile at address 0x07.
    function _ecMul(uint256[2] memory p, uint256 s) internal view returns (uint256[2] memory r) {
        uint256[3] memory input_data;
        input_data[0] = p[0];
        input_data[1] = p[1];
        input_data[2] = s;
        assembly {
            if iszero(staticcall(gas(), 0x07, input_data, 0x60, r, 0x40)) {
                revert(0, 0)
            }
        }
    }

    /// @dev Pairing check using the precompile at address 0x08.
    function _ecPairing(
        uint256[2] memory a1, uint256[2][2] calldata b1,
        uint256[2] memory a2, uint256[2][2] memory b2,
        uint256[2] memory a3, uint256[2][2] memory b3,
        uint256[2] calldata a4, uint256[2][2] memory b4
    ) internal view returns (bool) {
        // EIP-197 precompile: G2 points passed directly from snarkjs format.
        // No coordinate swapping -- snarkjs exportSolidityCallData already provides correct order.
        uint256[24] memory input_data;
        input_data[0] = a1[0]; input_data[1] = a1[1];
        input_data[2] = b1[0][1]; input_data[3] = b1[0][0];
        input_data[4] = b1[1][1]; input_data[5] = b1[1][0];

        input_data[6] = a2[0]; input_data[7] = a2[1];
        input_data[8] = b2[0][1]; input_data[9] = b2[0][0];
        input_data[10] = b2[1][1]; input_data[11] = b2[1][0];

        input_data[12] = a3[0]; input_data[13] = a3[1];
        input_data[14] = b3[0][1]; input_data[15] = b3[0][0];
        input_data[16] = b3[1][1]; input_data[17] = b3[1][0];

        input_data[18] = a4[0]; input_data[19] = a4[1];
        input_data[20] = b4[0][1]; input_data[21] = b4[0][0];
        input_data[22] = b4[1][1]; input_data[23] = b4[1][0];

        uint256[1] memory result;
        assembly {
            if iszero(staticcall(gas(), 0x08, input_data, 0x300, result, 0x20)) {
                revert(0, 0)
            }
        }
        return result[0] == 1;
    }
}
