// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.24;

import "./EnterpriseRegistry.sol";

/// @title StateCommitment
/// @notice Per-enterprise state root chains with integrated Groth16 ZK proof verification.
/// @dev Maintains an append-only chain of state roots for each enterprise. Each batch
///      submission advances the chain head atomically after verifying a Groth16 proof.
///      Layout A (Minimal): 32 bytes of new state per batch (root only). Batch metadata
///      is emitted via events, not stored on-chain, to stay under 300K gas per submission.
///
/// [Spec: validium/specs/units/2026-03-state-commitment/1-formalization/v0-analysis/specs/StateCommitment/StateCommitment.tla]
///
/// Safety invariants enforced:
///   INV-S1 ChainContinuity: prevRoot must match currentRoot before any state update
///   INV-S2 ProofBeforeState: ZK proof verified before state mutation (atomic)
///   NoGap: batch IDs are auto-incremented (no caller-supplied ID)
///   NoReversal: initialized enterprise currentRoot is always a valid root
///   InitBeforeBatch: only initialized enterprises can submit batches
///   GlobalCountIntegrity: totalBatchesCommitted == sum of all enterprise batchCounts
contract StateCommitment {
    // -----------------------------------------------------------------------
    // Types
    // -----------------------------------------------------------------------

    /// @dev Groth16 verifying key generated by SnarkJS trusted setup.
    struct VerifyingKey {
        uint256[2] alfa1;
        uint256[2][2] beta2;
        uint256[2][2] gamma2;
        uint256[2][2] delta2;
        uint256[2][] IC;
    }

    /// @dev Per-enterprise state chain head. Packed into 2 storage slots.
    /// [Spec: currentRoot, batchCount, initialized variables]
    struct EnterpriseState {
        bytes32 currentRoot;    // Slot 1: current chain head (32 bytes)
        uint64 batchCount;      // Slot 2: next batch ID, auto-incrementing (8 bytes)
        uint64 lastTimestamp;   // Slot 2: last submission timestamp (8 bytes)
        bool initialized;       // Slot 2: initialization flag (1 byte)
    }

    // -----------------------------------------------------------------------
    // State
    // -----------------------------------------------------------------------

    /// @notice Network admin address (Base Computing).
    address public admin;

    /// @notice Reference to the EnterpriseRegistry for authorization checks.
    EnterpriseRegistry public immutable enterpriseRegistry;

    /// @dev Groth16 verifying key for the state transition circuit.
    VerifyingKey private vk;

    /// @notice Whether the verifying key has been configured.
    bool public verifyingKeySet;

    /// @notice Per-enterprise state chain head.
    /// [Spec: currentRoot, batchCount, initialized]
    mapping(address => EnterpriseState) public enterprises;

    /// @notice Per-enterprise batch history: enterprise -> batchId -> stateRoot.
    /// [Spec: batchHistory]
    mapping(address => mapping(uint256 => bytes32)) public batchRoots;

    /// @notice Global counter of all committed batches across all enterprises.
    /// [Spec: totalCommitted]
    uint256 public totalBatchesCommitted;

    // -----------------------------------------------------------------------
    // Events
    // -----------------------------------------------------------------------

    /// @dev Emitted when an enterprise submits a valid batch.
    /// [Spec: SubmitBatch action -- state transition recorded]
    event BatchCommitted(
        address indexed enterprise,
        uint256 indexed batchId,
        bytes32 prevRoot,
        bytes32 newRoot,
        uint256 timestamp
    );

    /// @dev Emitted when an enterprise's state chain is initialized.
    /// [Spec: InitializeEnterprise action]
    event EnterpriseInitialized(
        address indexed enterprise,
        bytes32 genesisRoot,
        uint256 timestamp
    );

    // -----------------------------------------------------------------------
    // Errors
    // -----------------------------------------------------------------------

    error OnlyAdmin();
    error NotAuthorized();
    error VerifyingKeyNotSet();
    error EnterpriseNotInitialized();
    error EnterpriseAlreadyInitialized();
    /// @dev ChainContinuity violation: expected vs provided prevRoot.
    error RootChainBroken(bytes32 expected, bytes32 provided);
    error InvalidProof();

    // -----------------------------------------------------------------------
    // Modifiers
    // -----------------------------------------------------------------------

    modifier onlyAdmin() {
        if (msg.sender != admin) revert OnlyAdmin();
        _;
    }

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    /// @notice Deploys the StateCommitment contract.
    /// @param _enterpriseRegistry Address of the EnterpriseRegistry contract.
    constructor(address _enterpriseRegistry) {
        admin = msg.sender;
        enterpriseRegistry = EnterpriseRegistry(_enterpriseRegistry);
    }

    // -----------------------------------------------------------------------
    // Admin Functions
    // -----------------------------------------------------------------------

    /// @notice Sets the Groth16 verifying key for the state transition circuit.
    /// @dev Only callable by admin. Must match the circuit used for proving.
    /// @param _alfa1 The alfa1 point of the verifying key.
    /// @param _beta2 The beta2 point of the verifying key.
    /// @param _gamma2 The gamma2 point of the verifying key.
    /// @param _delta2 The delta2 point of the verifying key.
    /// @param _IC The IC points of the verifying key.
    function setVerifyingKey(
        uint256[2] calldata _alfa1,
        uint256[2][2] calldata _beta2,
        uint256[2][2] calldata _gamma2,
        uint256[2][2] calldata _delta2,
        uint256[2][] calldata _IC
    ) external onlyAdmin {
        vk.alfa1 = _alfa1;
        vk.beta2 = _beta2;
        vk.gamma2 = _gamma2;
        vk.delta2 = _delta2;
        delete vk.IC;
        for (uint256 i = 0; i < _IC.length; i++) {
            vk.IC.push(_IC[i]);
        }
        verifyingKeySet = true;
    }

    /// @notice Initializes an enterprise's state chain with a genesis root.
    /// @dev Must be called before the enterprise can submit batches. Admin only.
    ///      The genesis root represents the initial state of the enterprise's
    ///      Sparse Merkle Tree (typically the hash of an empty tree).
    ///
    /// [Spec: InitializeEnterprise(e, genesisRoot)]
    ///   Guard: ~initialized[e]
    ///   Effect: currentRoot' = genesisRoot, initialized' = TRUE
    ///
    /// @param enterprise The address of the enterprise to initialize.
    /// @param genesisRoot The initial state root (hash of empty SMT).
    function initializeEnterprise(
        address enterprise,
        bytes32 genesisRoot
    ) external onlyAdmin {
        if (enterprises[enterprise].initialized) revert EnterpriseAlreadyInitialized();

        enterprises[enterprise] = EnterpriseState({
            currentRoot: genesisRoot,
            batchCount: 0,
            lastTimestamp: uint64(block.timestamp),
            initialized: true
        });

        emit EnterpriseInitialized(enterprise, genesisRoot, block.timestamp);
    }

    // -----------------------------------------------------------------------
    // Core Function
    // -----------------------------------------------------------------------

    /// @notice Submits a batch with ZK proof. Verifies proof and advances the state chain.
    /// @dev Enforces all TLA+ safety invariants atomically:
    ///   INV-S1 ChainContinuity: prevStateRoot must match current chain head
    ///   INV-S2 ProofBeforeState: Groth16 proof verified before any state mutation
    ///   NoGap: batchId = batchCount (auto-incremented, not caller-supplied)
    ///   InitBeforeBatch: enterprise must be initialized
    ///
    /// [Spec: SubmitBatch(e, prevRoot, newRoot, proofIsValid)]
    ///   Guard 1: initialized[e]
    ///   Guard 2: prevRoot = currentRoot[e]
    ///   Guard 3: proofIsValid = TRUE
    ///   Effect: currentRoot' = newRoot, batchCount' = batchCount + 1,
    ///           batchHistory'[batchCount] = newRoot, totalCommitted' + 1
    ///
    /// @param prevStateRoot The state root before this batch (must match chain head).
    /// @param newStateRoot The state root after applying this batch.
    /// @param a Groth16 proof point A.
    /// @param b Groth16 proof point B.
    /// @param c Groth16 proof point C.
    /// @param publicSignals Public inputs to the state transition circuit.
    function submitBatch(
        bytes32 prevStateRoot,
        bytes32 newStateRoot,
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata publicSignals
    ) external {
        // Verifying key must be configured
        if (!verifyingKeySet) revert VerifyingKeyNotSet();

        // Authorization: caller must be a registered, active enterprise
        if (!enterpriseRegistry.isAuthorized(msg.sender)) revert NotAuthorized();

        EnterpriseState storage es = enterprises[msg.sender];

        // InitBeforeBatch: enterprise must be initialized
        if (!es.initialized) revert EnterpriseNotInitialized();

        // INV-S1: ChainContinuity -- prevRoot must match current chain head
        if (es.currentRoot != prevStateRoot) {
            revert RootChainBroken(es.currentRoot, prevStateRoot);
        }

        // INV-S2: ProofBeforeState -- verify ZK proof BEFORE any state change
        bool valid = _verifyProof(a, b, c, publicSignals);
        if (!valid) revert InvalidProof();

        // NoGap: batch ID is always sequential (es.batchCount is the next ID)
        uint256 batchId = es.batchCount;

        // State update (atomic with proof verification)
        es.currentRoot = newStateRoot;
        es.batchCount = uint64(batchId + 1);
        es.lastTimestamp = uint64(block.timestamp);

        // History: store only the new state root (32 bytes = 1 storage slot)
        batchRoots[msg.sender][batchId] = newStateRoot;

        // GlobalCountIntegrity: increment global counter
        totalBatchesCommitted++;

        emit BatchCommitted(
            msg.sender,
            batchId,
            prevStateRoot,
            newStateRoot,
            block.timestamp
        );
    }

    // -----------------------------------------------------------------------
    // View Functions
    // -----------------------------------------------------------------------

    /// @notice Returns the current state root for an enterprise.
    /// @param enterprise The enterprise address to query.
    /// @return The current chain head root.
    function getCurrentRoot(address enterprise) external view returns (bytes32) {
        return enterprises[enterprise].currentRoot;
    }

    /// @notice Returns the state root stored for a specific batch.
    /// @param enterprise The enterprise address.
    /// @param batchId The batch index to query.
    /// @return The state root committed at that batch.
    function getBatchRoot(
        address enterprise,
        uint256 batchId
    ) external view returns (bytes32) {
        return batchRoots[enterprise][batchId];
    }

    /// @notice Returns the batch count (number of committed batches) for an enterprise.
    /// @param enterprise The enterprise address.
    /// @return The number of batches committed by this enterprise.
    function getBatchCount(address enterprise) external view returns (uint256) {
        return enterprises[enterprise].batchCount;
    }

    /// @notice Verifies that a specific root was committed at a given batch index.
    /// @param enterprise The enterprise address.
    /// @param batchId The batch index.
    /// @param root The root to verify.
    /// @return True if the root matches the one committed at batchId.
    function isCommittedRoot(
        address enterprise,
        uint256 batchId,
        bytes32 root
    ) external view returns (bool) {
        return batchRoots[enterprise][batchId] == root;
    }

    // -----------------------------------------------------------------------
    // Internal: Groth16 Verification (Inline)
    // -----------------------------------------------------------------------

    /// @dev Verifies a Groth16 proof against the stored verifying key.
    ///      Inline implementation avoids cross-contract call overhead (~56K gas saved).
    ///      Uses EIP-196 (ecAdd, ecMul) and EIP-197 (ecPairing) precompiles.
    ///      Virtual to allow test harness override.
    function _verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata input
    ) internal view virtual returns (bool) {
        require(input.length + 1 == vk.IC.length, "Invalid input length");

        uint256[2] memory vk_x = [vk.IC[0][0], vk.IC[0][1]];

        for (uint256 i = 0; i < input.length; i++) {
            uint256[2] memory mul_result = _ecMul(vk.IC[i + 1], input[i]);
            vk_x = _ecAdd(vk_x, mul_result);
        }

        return _ecPairing(
            _negate(a),
            b,
            vk.alfa1,
            vk.beta2,
            vk_x,
            vk.gamma2,
            c,
            vk.delta2
        );
    }

    /// @dev Negates a point on the BN254 curve.
    function _negate(
        uint256[2] calldata p
    ) internal pure returns (uint256[2] memory) {
        uint256 q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
        if (p[0] == 0 && p[1] == 0) return [uint256(0), uint256(0)];
        return [p[0], q - (p[1] % q)];
    }

    /// @dev Elliptic curve addition using the precompile at address 0x06 (EIP-196).
    function _ecAdd(
        uint256[2] memory p1,
        uint256[2] memory p2
    ) internal view returns (uint256[2] memory r) {
        uint256[4] memory input_data;
        input_data[0] = p1[0];
        input_data[1] = p1[1];
        input_data[2] = p2[0];
        input_data[3] = p2[1];
        assembly {
            if iszero(staticcall(gas(), 0x06, input_data, 0x80, r, 0x40)) {
                revert(0, 0)
            }
        }
    }

    /// @dev Elliptic curve scalar multiplication using the precompile at address 0x07 (EIP-196).
    function _ecMul(
        uint256[2] memory p,
        uint256 s
    ) internal view returns (uint256[2] memory r) {
        uint256[3] memory input_data;
        input_data[0] = p[0];
        input_data[1] = p[1];
        input_data[2] = s;
        assembly {
            if iszero(staticcall(gas(), 0x07, input_data, 0x60, r, 0x40)) {
                revert(0, 0)
            }
        }
    }

    /// @dev Pairing check using the precompile at address 0x08 (EIP-197).
    function _ecPairing(
        uint256[2] memory a1, uint256[2][2] calldata b1,
        uint256[2] memory a2, uint256[2][2] memory b2,
        uint256[2] memory a3, uint256[2][2] memory b3,
        uint256[2] calldata a4, uint256[2][2] memory b4
    ) internal view returns (bool) {
        uint256[24] memory input_data;
        input_data[0] = a1[0]; input_data[1] = a1[1];
        input_data[2] = b1[0][1]; input_data[3] = b1[0][0];
        input_data[4] = b1[1][1]; input_data[5] = b1[1][0];

        input_data[6] = a2[0]; input_data[7] = a2[1];
        input_data[8] = b2[0][1]; input_data[9] = b2[0][0];
        input_data[10] = b2[1][1]; input_data[11] = b2[1][0];

        input_data[12] = a3[0]; input_data[13] = a3[1];
        input_data[14] = b3[0][1]; input_data[15] = b3[0][0];
        input_data[16] = b3[1][1]; input_data[17] = b3[1][0];

        input_data[18] = a4[0]; input_data[19] = a4[1];
        input_data[20] = b4[0][1]; input_data[21] = b4[0][0];
        input_data[22] = b4[1][1]; input_data[23] = b4[1][0];

        uint256[1] memory result;
        assembly {
            if iszero(staticcall(gas(), 0x08, input_data, 0x300, result, 0x20)) {
                revert(0, 0)
            }
        }
        return result[0] == 1;
    }
}
