// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.24;

/// @title IHalo2Verifier
/// @notice Interface for the self-contained Halo2 verifier (VK embedded).
/// @dev Generated by halo2-solidity-verifier's render() method.
///      The verifier has VK constants embedded in its bytecode, so no
///      external VK contract address is needed.
interface IHalo2Verifier {
    function verifyProof(
        bytes calldata proof,
        uint256[] calldata instances
    ) external view returns (bool);
}

/// @title Halo2PlonkVerifier
/// @notice Wrapper that forwards proof verification to the generated
///         Halo2Verifier contract.
///
/// @dev BasisRollupV2 calls verifyProof(proof, publicInputs).
///      This wrapper forwards to the self-contained Halo2Verifier which
///      has VK constants embedded (generated by render(), not render_separately()).
contract Halo2PlonkVerifier {
    address public admin;
    address public halo2Verifier;
    bool public configured;

    event Configured(address indexed verifier);

    error OnlyAdmin();
    error NotConfigured();
    error AlreadyConfigured();

    modifier onlyAdmin() {
        if (msg.sender != admin) revert OnlyAdmin();
        _;
    }

    constructor() {
        admin = msg.sender;
    }

    /// @notice Configure the Halo2 verifier contract address.
    function configure(address _verifier) external onlyAdmin {
        if (configured) revert AlreadyConfigured();
        halo2Verifier = _verifier;
        configured = true;
        emit Configured(_verifier);
    }

    /// @notice Verify a PLONK-KZG proof using the generated Halo2 verifier.
    /// @dev Matches the IPlonkVerifier interface: verifyProof(bytes, uint256[])
    function verifyProof(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) external view returns (bool valid) {
        if (!configured) revert NotConfigured();
        return IHalo2Verifier(halo2Verifier).verifyProof(proof, publicInputs);
    }
}
