// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.24;

import "./EnterpriseRegistry.sol";

/// @title IGroth16Verifier
/// @dev Interface for the snarkjs-generated Groth16Verifier contract.
interface IGroth16Verifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool);
}

/// @title StateCommitment
/// @notice Per-enterprise state root chains with delegated Groth16 ZK proof verification.
/// @dev Maintains an append-only chain of state roots for each enterprise. Each batch
///      submission advances the chain head atomically after verifying a Groth16 proof
///      via an external verifier contract (generated by snarkjs trusted setup).
///
/// [Spec: validium/specs/units/2026-03-state-commitment/1-formalization/v0-analysis/specs/StateCommitment/StateCommitment.tla]
///
/// Safety invariants enforced:
///   INV-S1 ChainContinuity: prevRoot must match currentRoot before any state update
///   INV-S2 ProofBeforeState: ZK proof verified before state mutation (atomic)
///   NoGap: batch IDs are auto-incremented (no caller-supplied ID)
///   NoReversal: initialized enterprise currentRoot is always a valid root
///   InitBeforeBatch: only initialized enterprises can submit batches
///   GlobalCountIntegrity: totalBatchesCommitted == sum of all enterprise batchCounts
contract StateCommitment {
    // -----------------------------------------------------------------------
    // Types
    // -----------------------------------------------------------------------

    /// @dev Per-enterprise state chain head. Packed into 2 storage slots.
    /// [Spec: currentRoot, batchCount, initialized variables]
    struct EnterpriseState {
        bytes32 currentRoot;    // Slot 1: current chain head (32 bytes)
        uint64 batchCount;      // Slot 2: next batch ID, auto-incrementing (8 bytes)
        uint64 lastTimestamp;   // Slot 2: last submission timestamp (8 bytes)
        bool initialized;       // Slot 2: initialization flag (1 byte)
    }

    // -----------------------------------------------------------------------
    // State
    // -----------------------------------------------------------------------

    /// @notice Network admin address (Base Computing).
    address public admin;

    /// @notice Reference to the EnterpriseRegistry for authorization checks.
    EnterpriseRegistry public immutable enterpriseRegistry;

    /// @notice External Groth16 verifier contract (generated by snarkjs).
    IGroth16Verifier public verifier;

    /// @notice Whether the verifier has been configured.
    bool public verifyingKeySet;

    /// @notice Per-enterprise state chain head.
    /// [Spec: currentRoot, batchCount, initialized]
    mapping(address => EnterpriseState) public enterprises;

    /// @notice Per-enterprise batch history: enterprise -> batchId -> stateRoot.
    /// [Spec: batchHistory]
    mapping(address => mapping(uint256 => bytes32)) public batchRoots;

    /// @notice Global counter of all committed batches across all enterprises.
    /// [Spec: totalCommitted]
    uint256 public totalBatchesCommitted;

    // -----------------------------------------------------------------------
    // Events
    // -----------------------------------------------------------------------

    /// @dev Emitted when an enterprise submits a valid batch.
    /// [Spec: SubmitBatch action -- state transition recorded]
    event BatchCommitted(
        address indexed enterprise,
        uint256 indexed batchId,
        bytes32 prevRoot,
        bytes32 newRoot,
        uint256 timestamp
    );

    /// @dev Emitted when an enterprise's state chain is initialized.
    /// [Spec: InitializeEnterprise action]
    event EnterpriseInitialized(
        address indexed enterprise,
        bytes32 genesisRoot,
        uint256 timestamp
    );

    // -----------------------------------------------------------------------
    // Errors
    // -----------------------------------------------------------------------

    error OnlyAdmin();
    error NotAuthorized();
    error VerifyingKeyNotSet();
    error EnterpriseNotInitialized();
    error EnterpriseAlreadyInitialized();
    /// @dev ChainContinuity violation: expected vs provided prevRoot.
    error RootChainBroken(bytes32 expected, bytes32 provided);
    error InvalidProof();

    // -----------------------------------------------------------------------
    // Modifiers
    // -----------------------------------------------------------------------

    modifier onlyAdmin() {
        if (msg.sender != admin) revert OnlyAdmin();
        _;
    }

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    /// @notice Deploys the StateCommitment contract.
    /// @param _enterpriseRegistry Address of the EnterpriseRegistry contract.
    constructor(address _enterpriseRegistry) {
        admin = msg.sender;
        enterpriseRegistry = EnterpriseRegistry(_enterpriseRegistry);
    }

    // -----------------------------------------------------------------------
    // Admin Functions
    // -----------------------------------------------------------------------

    /// @notice Sets the external Groth16 verifier contract.
    /// @dev The verifier is generated by snarkjs and has the verifying key baked in.
    ///      This replaces the previous setVerifyingKey approach which had storage
    ///      layout issues with uint256[2][2] G2 points.
    /// @param _verifier Address of the deployed Groth16Verifier contract.
    function setVerifier(address _verifier) external onlyAdmin {
        verifier = IGroth16Verifier(_verifier);
        verifyingKeySet = true;
    }

    /// @notice Initializes an enterprise's state chain with a genesis root.
    /// @dev Must be called before the enterprise can submit batches. Admin only.
    ///
    /// [Spec: InitializeEnterprise(e, genesisRoot)]
    ///   Guard: ~initialized[e]
    ///   Effect: currentRoot' = genesisRoot, initialized' = TRUE
    ///
    /// @param enterprise The address of the enterprise to initialize.
    /// @param genesisRoot The initial state root (hash of empty SMT).
    function initializeEnterprise(
        address enterprise,
        bytes32 genesisRoot
    ) external onlyAdmin {
        if (enterprises[enterprise].initialized) revert EnterpriseAlreadyInitialized();

        enterprises[enterprise] = EnterpriseState({
            currentRoot: genesisRoot,
            batchCount: 0,
            lastTimestamp: uint64(block.timestamp),
            initialized: true
        });

        emit EnterpriseInitialized(enterprise, genesisRoot, block.timestamp);
    }

    // -----------------------------------------------------------------------
    // Core Function
    // -----------------------------------------------------------------------

    /// @notice Submits a batch with ZK proof. Verifies proof and advances the state chain.
    /// @dev Enforces all TLA+ safety invariants atomically:
    ///   INV-S1 ChainContinuity: prevStateRoot must match current chain head
    ///   INV-S2 ProofBeforeState: Groth16 proof verified before any state mutation
    ///   NoGap: batchId = batchCount (auto-incremented, not caller-supplied)
    ///   InitBeforeBatch: enterprise must be initialized
    ///
    /// @param prevStateRoot The state root before this batch (must match chain head).
    /// @param newStateRoot The state root after applying this batch.
    /// @param a Groth16 proof point A.
    /// @param b Groth16 proof point B.
    /// @param c Groth16 proof point C.
    /// @param publicSignals Public inputs to the state transition circuit.
    function submitBatch(
        bytes32 prevStateRoot,
        bytes32 newStateRoot,
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata publicSignals
    ) external {
        // Verifying key must be configured
        if (!verifyingKeySet) revert VerifyingKeyNotSet();

        // Authorization: caller must be a registered, active enterprise
        if (!enterpriseRegistry.isAuthorized(msg.sender)) revert NotAuthorized();

        EnterpriseState storage es = enterprises[msg.sender];

        // InitBeforeBatch: enterprise must be initialized
        if (!es.initialized) revert EnterpriseNotInitialized();

        // INV-S1: ChainContinuity -- prevRoot must match current chain head
        if (es.currentRoot != prevStateRoot) {
            revert RootChainBroken(es.currentRoot, prevStateRoot);
        }

        // INV-S2: ProofBeforeState -- verify ZK proof BEFORE any state change
        // Delegate to external Groth16Verifier (generated by snarkjs trusted setup).
        // The verifier has the VK baked in as constants, avoiding storage layout issues.
        require(publicSignals.length == 4, "Expected 4 public signals");
        bool valid = verifier.verifyProof(
            a, b, c,
            [publicSignals[0], publicSignals[1], publicSignals[2], publicSignals[3]]
        );
        if (!valid) revert InvalidProof();

        // NoGap: batch ID is always sequential (es.batchCount is the next ID)
        uint256 batchId = es.batchCount;

        // State update (atomic with proof verification)
        es.currentRoot = newStateRoot;
        es.batchCount = uint64(batchId + 1);
        es.lastTimestamp = uint64(block.timestamp);

        // History: store only the new state root (32 bytes = 1 storage slot)
        batchRoots[msg.sender][batchId] = newStateRoot;

        // GlobalCountIntegrity: increment global counter
        totalBatchesCommitted++;

        emit BatchCommitted(
            msg.sender,
            batchId,
            prevStateRoot,
            newStateRoot,
            block.timestamp
        );
    }

    // -----------------------------------------------------------------------
    // View Functions
    // -----------------------------------------------------------------------

    /// @notice Returns the current state root for an enterprise.
    function getCurrentRoot(address enterprise) external view returns (bytes32) {
        return enterprises[enterprise].currentRoot;
    }

    /// @notice Returns the state root stored for a specific batch.
    function getBatchRoot(address enterprise, uint256 batchId) external view returns (bytes32) {
        return batchRoots[enterprise][batchId];
    }

    /// @notice Returns the batch count for an enterprise.
    function getBatchCount(address enterprise) external view returns (uint256) {
        return enterprises[enterprise].batchCount;
    }

    /// @notice Verifies that a specific root was committed at a given batch index.
    function isCommittedRoot(address enterprise, uint256 batchId, bytes32 root) external view returns (bool) {
        return batchRoots[enterprise][batchId] == root;
    }
}
